# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  db:
    image: mysql:latest
    restart: always
    expose:
      # Opens port 3308 on the container
      - '3308'
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testuserpassword
      MYSQL_DATABASE: todolist
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuserpassword
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
  mcgassignmenttodolist:
    depends_on:
      - db
    image: mcgassignmenttodolist
    build:
      context: .
      dockerfile: src/MCGAssignment.TodoList/Dockerfile
    ports:
      - 5006:5006
  mcgassignmenttodolist-client:
    depends_on:
      - mcgassignmenttodolist
    image: mcgassignmenttodolist-client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 3939:3939

volumes:
  db:
    driver: local
